### ISSUE TITLE
how to compile it?

### ISSUE THREAD

**Issue by Arvrairobo** [iantv/VirtuaHairStyle#1]
i always get this error,

gcc main.cpp -lstdc++main.cpp:2:21: fatal error: GL\glew.h: No such file or directory
compilation terminated.

how is the app working? any demo?

**Comment by iantv** [comment]
I pushed source without third-party libraries. You should use glut, glew, dlib, opencv. It was educational project. I worked alone, so I didn't write documentation for compiling and using third-party libraries. 
App working was recorded for this video https://www.youtube.com/watch?v=JNBwUjA2mGQ&feature=youtu.be

**Comment by iantv** [comment]
Later, perhaps in this or next week, I will try push another version of app created on Qt, so you will mustn't use glut.

**Comment by Arvrairobo** [comment]
wow this is exactly i was looking for , so eager to wait for the final version

but i have a question why you have used C++ ? is it possible to get the same output in other technology?

**Comment by Arvrairobo** [comment]
https://github.com/Huey-H/LocalHairstylist this is similar app, but not accurate as yours , i am not sure why?

**Comment by iantv** [comment]
Firstly I wanted use Unity, but assets of opencv and dlib was not free. Dlib and opencv use c++, most of samples and tutorials has code written in c++, that's why I chose C++. Of course, you can choose any another language. Try, I will not promise the same result, but try.

**Comment by Arvrairobo** [comment]
yes i am trying with python and nodejs at the moment, lets see

but can you please explain how you are displaying hairstyle on top of the head, whats the logic to place  hairstyle on head plus what distance to camera are you specifying so that it is looking more accurate?

**Comment by iantv** [comment]
Read about Perspective-n-Point(PnP) problem, about methods used to solve.

**Comment by Arvrairobo** [comment]
Hello @iantv any update on the Qt Version of the app?

**Comment by iantv** [comment]
Now you can watch branch "qt"

**Comment by Arvrairobo** [comment]
any readme file, how to run it?

**Comment by Arvrairobo** [comment]
i have installed QT and Qt Creator, opened the pro file and running it with qmake it shows below 3 errors
----------------
/Users/Documents/arhair/VideoPlayer.h:8: error: 'opencv2/core/core.hpp' file not found
#include <opencv2/core/core.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
-------------------------
/Users/Documents/arhair/MainWindow.h:6: In file included from ../arhair/MainWindow.h:6:


----------------------

/Users/Documents/arhair/main.cpp:1: In file included from ../arhair/main.cpp:1:

**Comment by iantv** [comment]
Please reread my first answer!
1. I didn't write documentation for compiling, when I will have more time, I will it.
2. I wrote you about using third-party libraries such as opencv and dlib.

So, you should change paths in variables INCLUDEPATH and LIBS of the pro file. Specify your directories of opencv and dlib.
