### ISSUE TITLE
seems something wrong in shader

### ISSUE THREAD

**Issue by BlurryLight** [iantv/VirtuaHairStyle#2]
Hey iantv!
Your project is great. I have yet succefully compiled your project since my OpenCV is broken. I've read part of your code and found something weird.

1. It sees your git had done something do your background.vert . 
https://github.com/iantv/AR-Hair/blob/538afa29cbf3ed9a8925ee2f829c4e38ae579e47/Resources/shaders/background.vert#L8

2. I'm a lillte confused about the magic number in lines from there.  Could you help me with more information about it?
https://github.com/iantv/AR-Hair/blob/538afa29cbf3ed9a8925ee2f829c4e38ae579e47/PoseEstimation.cpp#L21

**Comment by iantv** [comment]
1. Oh, thanks. I fixed this shader. Now, you can pull data from repository 
2. This points are (x, y, z) coordinates from 3d model matched to 2D points on image/frame from camera.
You can use points of your 3D model of head and to watch coordinates using Blender3D in Edit mode with selected object (3d head model).

**Comment by BlurryLight** [comment]
Hey! Thanks for your quick reply! 
I have mannually fixed the error and managed to get my OpenCV work. However, It looks like you've forgot to upload the "hair_v1.obj" . It should be in the path './Resources/3D models/hair/hair_v1.obj'.

Now my good friend QtCreator keep throwing error like this
```
:-1: error: No rule to make target '../../Resources/3D models/hair/hair_v1.obj', needed by 'qrc_application.cpp'.  Stop.
```

Could you share the original obj file?

**Comment by iantv** [comment]
Sorry, I couldn't find a 3d model of a head. But I used from this link
https://www.turbosquid.com/FullPreview/Index.cfm/ID/256001
This head was free when I used it

**Comment by iantv** [comment]
You can use another 3d model of a head, you just should exchange coordinates of keypoints in this. https://github.com/iantv/AR-Hair/blob/538afa29cbf3ed9a8925ee2f829c4e38ae579e47/PoseEstimation.cpp#L21
